package com.dvd.ui;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.List;

import org.json.JSONObject;

import com.dvd.domain.Dvd;
import com.dvd.hibernate.doa.DVDCopyDao;
import com.dvd.hibernate.domain.DVD;
import com.dvd.prop.PropReader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class AddDVD extends javax.swing.JFrame {
	private boolean isServiceOn = false;

	/**
	 * Creates new form ShopUI
	 */
	public AddDVD() {
		initComponents();

		PropReader properties = new PropReader();
		isServiceOn = properties.getConnectionProp();
		System.out.println(isServiceOn);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		label1 = new java.awt.Label();
		label2 = new java.awt.Label();
		label4 = new java.awt.Label();
		label5 = new java.awt.Label();
		dvdTitle = new java.awt.TextField();
		label6 = new java.awt.Label();
		dvdYearReleased = new java.awt.TextField();
		mainActors = new java.awt.TextField();
		rating = new javax.swing.JComboBox();
		jLabel1 = new javax.swing.JLabel();
		label8 = new java.awt.Label();
		definition = new javax.swing.JComboBox();
		addDVD = new javax.swing.JButton();
		errorLabel = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setBackground(new java.awt.Color(106, 161, 172));
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(23, 193, 111));
		jPanel1.setForeground(new java.awt.Color(254, 238, 238));

		label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		label1.setFont(new java.awt.Font("Ubuntu Medium", 0, 48)); // NOI18N
		label1.setForeground(new java.awt.Color(254, 254, 254));
		label1.setText("DVD Shop");

		label2.setFont(new java.awt.Font("Ubuntu Medium", 0, 16)); // NOI18N
		label2.setForeground(new java.awt.Color(254, 254, 254));
		label2.setText("DVD Title");

		label4.setFont(new java.awt.Font("Ubuntu Medium", 0, 16)); // NOI18N
		label4.setForeground(new java.awt.Color(254, 254, 254));
		label4.setText("Year Released");

		label5.setFont(new java.awt.Font("Ubuntu Medium", 0, 16)); // NOI18N
		label5.setForeground(new java.awt.Color(254, 254, 254));
		label5.setText("Main Actors");

		dvdTitle.setFont(new java.awt.Font("Ubuntu Medium", 1, 14)); // NOI18N
		dvdTitle.setName("txtCus"); // NOI18N
		dvdTitle.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dvdTitleActionPerformed(evt);
			}
		});

		label6.setFont(new java.awt.Font("Ubuntu Medium", 0, 16)); // NOI18N
		label6.setForeground(new java.awt.Color(254, 254, 254));
		label6.setText("IMDB Rating");

		dvdYearReleased.setFont(new java.awt.Font("Ubuntu Medium", 1, 14)); // NOI18N
		dvdYearReleased.setName("txtCusID"); // NOI18N
		dvdYearReleased.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				dvdYearReleasedActionPerformed(evt);
			}
		});

		mainActors.setFont(new java.awt.Font("Ubuntu Medium", 1, 14)); // NOI18N
		mainActors.setName("txtCusAdd"); // NOI18N

		rating.setFont(new java.awt.Font("Ubuntu Medium", 1, 14)); // NOI18N
		rating.setForeground(new java.awt.Color(34, 25, 25));
		rating.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
		rating.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				ratingActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Ubuntu Medium", 0, 24)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(254, 254, 254));
		jLabel1.setText("Add DVD");

		label8.setFont(new java.awt.Font("Ubuntu Medium", 0, 16)); // NOI18N
		label8.setForeground(new java.awt.Color(254, 254, 254));
		label8.setText("Definintion Format");

		definition.setFont(new java.awt.Font("Ubuntu Medium", 1, 14)); // NOI18N
		definition.setForeground(new java.awt.Color(34, 25, 25));
		definition.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"1080i", "720i", "normal" }));
		definition.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				definitionActionPerformed(evt);
			}
		});

		addDVD.setForeground(new java.awt.Color(1, 1, 1));
		addDVD.setText("Add DVD");
		addDVD.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				addDVDActionPerformed(evt);
			}
		});

		errorLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
		errorLabel.setForeground(new java.awt.Color(226, 33, 33));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addGap(0, 0, Short.MAX_VALUE)
										.addComponent(
												errorLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												275,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(114, 114, 114))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(156,
																				156,
																				156)
																		.addComponent(
																				label1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(206,
																				206,
																				206)
																		.addComponent(
																				jLabel1)))
										.addGap(0, 0, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(29,
																				29,
																				29)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								label2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								label4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								label5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								label6,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								label8,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(57,
																				57,
																				57)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addComponent(
																												mainActors,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												dvdYearReleased,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												dvdTitle,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												285,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addComponent(
																												rating,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												0,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												definition,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												93,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(191,
																				191,
																				191)
																		.addComponent(
																				addDVD,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				165,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(41, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												label1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(2, 2, 2)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								label2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								dvdTitle,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(27,
																				27,
																				27)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								dvdYearReleased,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								label4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(23,
																				23,
																				23)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												mainActors,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(25,
																												25,
																												25)
																										.addGroup(
																												jPanel1Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																rating,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																label6,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addComponent(
																								label5,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				definition,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																label8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												errorLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												28,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												addDVD,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												47,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(217, 217, 217)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 429,
								Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void definitionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_definitionActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_definitionActionPerformed

	private void ratingActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ratingActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_ratingActionPerformed

	private void dvdYearReleasedActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dvdYearReleasedActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_dvdYearReleasedActionPerformed

	private void dvdTitleActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_dvdTitleActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_dvdTitleActionPerformed

	private void addDVDActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addDVDActionPerformed

		String title = dvdTitle.getText();
		String year = dvdYearReleased.getText();
		String actors = mainActors.getText();
		String ratings = rating.getSelectedItem().toString();
		String definitions = definition.getSelectedItem().toString();

		if (title == null || title.isEmpty()) {
			errorLabel.setForeground(Color.RED);
			errorLabel.setText("Please Enter a DVD Title");

		} else {

			try {
				if (isServiceOn) {
					String result = "";
					String url1 = "http://localhost:8080/addDVD?title="
							+ URLEncoder.encode(title, "UTF-8").replace("+",
									"%20")
							+ "&year="
							+ year
							+ "&actors="
							+ URLEncoder.encode(actors, "UTF-8").replace("+",
									"%20") + "&ratings=" + ratings
							+ "&definitions=" + definitions;

					// String q = URLEncoder.encode(url1, "UTF-8").replace("+",
					// "%20");
					URL url = new URL(url1);

					URL obj = url;
					HttpURLConnection con = (HttpURLConnection) obj
							.openConnection();
					// con.setRequestProperty(CONTENT_LENGTH,
					// Integer.toString(content.getBytes().length));
					con.setRequestProperty("Accept-Charset", "UTF-8");
					con.setRequestProperty("Content-Type",
							"application/x-www-form-urlencoded");
					con.setRequestProperty("Content-Language", "en-US");
					// optional default is GET
					con.setRequestMethod("POST");
					// add request header
					con.setRequestProperty("User-Agent", "Mozilla/5.0");

					int responseCode = con.getResponseCode();
					System.out.println("\nSending 'GET' request to URL : "
							+ url);
					System.out.println("Response Code : " + responseCode);

					BufferedReader in = new BufferedReader(
							new InputStreamReader(con.getInputStream()));
					String inputLine;
					StringBuffer response = new StringBuffer();

					while ((inputLine = in.readLine()) != null) {
						response.append(inputLine);
					}
					in.close();

					// print result
					result = response.toString();
					// Parse to get translated text

					JSONObject jsonObject = new JSONObject(result);
					int code = jsonObject.getJSONObject("responseCode").getInt(
							"code");

					if (code == 201) {
						errorLabel.setForeground(Color.BLACK);
						errorLabel.setText("DVD Successfully Added.");
					} else {
						errorLabel.setForeground(Color.RED);
						errorLabel.setText("Adding DVD failed");
					}

				} else {
					com.dvd.hibernate.repo.DVDRepository repository = new com.dvd.hibernate.repo.DVDRepository();

					DVD dvd = new DVD(0, title, actors,
							Integer.parseInt(ratings), definitions, year);
					repository.createDVD(dvd);

					errorLabel.setForeground(Color.BLACK);
					errorLabel.setText("DVD Successfully Added.");
				}

			} catch (Exception e) {

				errorLabel.setForeground(Color.RED);
				errorLabel.setText("Adding DVD failed");

			}

		}

		System.out.println(title + year + actors + ratings + definitions);

	}// GEN-LAST:event_addDVDActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AddDVD.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AddDVD.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AddDVD.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AddDVD.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddDVD().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton addDVD;
	private javax.swing.JComboBox definition;
	private java.awt.TextField dvdTitle;
	private java.awt.TextField dvdYearReleased;
	private javax.swing.JLabel errorLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private java.awt.Label label1;
	private java.awt.Label label2;
	private java.awt.Label label4;
	private java.awt.Label label5;
	private java.awt.Label label6;
	private java.awt.Label label8;
	private java.awt.TextField mainActors;
	private javax.swing.JComboBox rating;
	// End of variables declaration//GEN-END:variables
}
