package com.dvd.ui;

import com.dvd.domain.User;
import com.dvd.hibernate.repo.UserRepository;
import com.dvd.prop.PropReader;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import org.json.JSONObject;
/**
 * 
 * @author amilai
 *
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Login extends javax.swing.JFrame {

	private boolean isServiceOn = false;

	/**
	 * Creates new form ShopUI
	 */
	public Login() {
		initComponents();
		setTitle("DVD Portal System");
		errorTagLabel.setVisible(false);
		PropReader properties = new PropReader();
		isServiceOn = properties.getConnectionProp();
		System.out.println(isServiceOn);
		// BufferedImage bi = null;
		// try {
		// bi = ImageIO.read(getClass().getResource("pic1.png"));
		// } catch (IOException ex) {
		// Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
		// }
		// ImageIcon image = new ImageIcon(bi);
		// picLabel.setIcon(image);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		errorTag = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		label1 = new java.awt.Label();
		jLabel1 = new javax.swing.JLabel();
		login = new javax.swing.JButton();
		picLabel = new javax.swing.JLabel();
		userIDTxt = new javax.swing.JTextField();
		errorTagLabel = new javax.swing.JLabel();

		errorTag.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
		errorTag.setForeground(new java.awt.Color(255, 0, 0));
		errorTag.setText("No result found");

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(106, 161, 172));
		setResizable(false);

		jPanel1.setBackground(new java.awt.Color(23, 193, 111));
		jPanel1.setForeground(new java.awt.Color(74, 74, 74));

		label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		label1.setFont(new java.awt.Font("Ubuntu Medium", 1, 36)); // NOI18N
		label1.setForeground(new java.awt.Color(254, 254, 254));
		label1.setText("DVD Shop User Login");

		jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N
		jLabel1.setForeground(new java.awt.Color(254, 254, 254));
		jLabel1.setText("Enter UserID");

		login.setText("Login");
		login.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				loginActionPerformed(evt);
			}
		});

		picLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/resources/pic7.jpg"))); // NOI18N
		picLabel.setBorder(javax.swing.BorderFactory.createLineBorder(
				new java.awt.Color(0, 0, 0), 2));

		userIDTxt.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				userIDTxtActionPerformed(evt);
			}
		});

		errorTagLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
		errorTagLabel.setForeground(new java.awt.Color(133, 20, 20));
		errorTagLabel.setText("Authentication Failed");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												errorTagLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												275,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(184, 184, 184))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(84,
																				84,
																				84)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addGap(46,
																												46,
																												46)
																										.addComponent(
																												label1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel1)
																										.addGap(20,
																												20,
																												20)
																										.addComponent(
																												userIDTxt,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												208,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												login,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												125,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(125,
																				125,
																				125)
																		.addComponent(
																				picLabel)))
										.addContainerGap(97, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												label1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																userIDTxt,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(login))
										.addGap(18, 18, 18)
										.addComponent(errorTagLabel)
										.addGap(18, 18, 18)
										.addComponent(
												picLabel,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												288,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(72, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
				javax.swing.GroupLayout.DEFAULT_SIZE,
				javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void loginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginActionPerformed
		errorTagLabel.setVisible(false);
		String userID = userIDTxt.getText();
		boolean isAuthenticated = false;
		if (userID != null && !userID.isEmpty()) {

			User user = null;

			try {
				int userIDInt = Integer.parseInt(userID);
				if (isServiceOn) {

					// Call Service
					// http://localhost:8080/getUser?userID=123
					String result = "";
					String url1 = "http://localhost:8080/getUser?userID="
							+ userIDInt;

					// String q = URLEncoder.encode(original, "UTF-8");
					URL url = new URL(url1);

					URL obj = url;
					HttpURLConnection con = (HttpURLConnection) obj
							.openConnection();

					// optional default is GET
					con.setRequestMethod("POST");

					// add request header
					con.setRequestProperty("User-Agent", "Mozilla/5.0");

					int responseCode = con.getResponseCode();
					System.out.println("\nSending 'GET' request to URL : "
							+ url);
					System.out.println("Response Code : " + responseCode);

					BufferedReader in = new BufferedReader(
							new InputStreamReader(con.getInputStream()));
					String inputLine;
					StringBuffer response = new StringBuffer();

					while ((inputLine = in.readLine()) != null) {
						response.append(inputLine);
					}
					in.close();

					// print result
					result = response.toString();
					// Parse to get translated text

					JSONObject jsonObject = new JSONObject(result);
					String userName = jsonObject.getJSONObject("body")
							.getString("userName").replace("&#39;", "'")
							.replace("&amp;", "&").replace("&#32", " ");
					int id = jsonObject.getJSONObject("body").getInt("userID");

					String userType = jsonObject.getJSONObject("body")
							.getString("userType").replace("&#39;", "'")
							.replace("&amp;", "&").replace("&#32", " ");

					System.out.println("Name:    " + userName);
					System.out.println("About:   " + userType);

					user = new User(userName, id, userType);
					if (userIDInt == id) {
						isAuthenticated = true;
					}

				} else {
					UserRepository repository = new UserRepository();
					user = repository.getUser(userIDInt);

					if (userIDInt == user.getUserID()) {
						isAuthenticated = true;
					}

				}

			} catch (Exception e) {
				System.err.println("error parsing" + e);
			}

			if (isAuthenticated) {
				errorTagLabel.setVisible(false);
				dispose();
				new MainUI(user).setVisible(true);
			} else {
				errorTagLabel.setText("Authentication Failed");
				errorTagLabel.setVisible(true);
			}

		} else {
			errorTagLabel.setText("Please enter login credentials");
			errorTagLabel.setVisible(true);
		}

	}// GEN-LAST:event_loginActionPerformed

	private void userIDTxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userIDTxtActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_userIDTxtActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel errorTag;
	private javax.swing.JLabel errorTagLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private java.awt.Label label1;
	private javax.swing.JButton login;
	private javax.swing.JLabel picLabel;
	private javax.swing.JTextField userIDTxt;
	// End of variables declaration//GEN-END:variables
}
